---
site_name: sunflower
site_description: 'A Sunflower docs'
docs_dir: docs
repo_name: 'AmazeIT/sunflower'
repo_url: 'https://github.com/AmazeIT/sunflower'
theme:
    name: material
    locale: ru
    highlightjs: true

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.0/styles/atom-one-light.min.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.0/highlight.min.js
plugins:
    - neoteroi.mkdocsoad:
    - simple:
    - kroki:
    - search:
        indexing: 'full'
        min_search_length: 2
# nav:
#     - 'Главная': 'README.md'
#     - 'Гайд' : 'guide.md'
#     - 'Devops':
#       - 'Main': devops/README.md
#       - 'Ansible': devops/ansible.md
