# Generated by Django 4.2.3 on 2023-07-24 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="LogRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("x509", "X509"),
                            ("ocsp", "OCSP"),
                        ],
                        max_length=12,
                        verbose_name="Module",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("GET", "Get one"),
                            ("GET[]", "Get list"),
                            ("POST", "Create"),
                            ("PUT", "Update"),
                            ("DELETE", "Delete"),
                        ],
                        max_length=12,
                        verbose_name="Action",
                    ),
                ),
                ("entity", models.CharField(max_length=32, verbose_name="Entity")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        )
    ]
