# Generated by Django 5.0.3 on 2024-03-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logentry",
            name="module",
            field=models.CharField(
                choices=[
                    ("system", "System"),
                    ("x509", "X509"),
                    ("ocsp", "OCSP"),
                    ("subjects", "Subjects"),
                ],
                max_length=12,
                verbose_name="Module",
            ),
        ),
    ]
