apiVersion: v1
kind: Service
metadata:
  name: {{ include "sunflower.fullname" . }}-docs
  labels:
    {{- include "sunflower.labels.docs" . | nindent 4 }}
spec:
  type: {{ .Values.docs.service.type }}
  ports:
    - port: {{ .Values.docs.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sunflower.selectorLabels.docs" . | nindent 4 }}
