{{- if .Values.docs.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sunflower.serviceAccountName.docs" . }}
  labels:
    {{- include "sunflower.labels.docs" . | nindent 4 }}
  {{- with .Values.docs.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.dockerconfigjson }}
imagePullSecrets:
  - name: {{ include "sunflower.fullname" . }}-registrysecret
{{- end }}
{{- end }}
