{{- if .Values.application.migrate.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-migrate-%s" (include "sunflower.fullname" .) (now | date "2006-01-02-15-04-05") | substr 0 60 }}
  labels:
    {{- include "sunflower.selectorLabels.application" . | nindent 4 }}
spec:
  backoffLimit: 15
  {{- if .Values.application.migrate.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ .Values.application.migrate.ttlSecondsAfterFinished }}
  {{- end }}
  template:
    metadata:
      name: {{ printf "%s-migrate-%s" (include "sunflower.fullname" .) (now | date "2006-01-02-15-04-05") }}
      {{- with .Values.application.podAnnotations }}
      annotations:
        random-annotation: {{ randAlphaNum 10 | lower }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sunflower.selectorLabels.application" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.application.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sunflower.serviceAccountName.application" . }}
      securityContext:
        {{- toYaml .Values.application.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}-migrate
        envFrom:
        - configMapRef:
            name: {{ include "sunflower.fullname" . }}
        securityContext:
          {{- toYaml .Values.application.securityContext | nindent 12 }}
        {{- if .Values.werf }}
        image: "{{ index .Values.werf.image "application"}}"
        {{- else }}
        image: "{{ .Values.application.image.repository }}:{{ .Values.application.image.tag | default .Chart.AppVersion }}"
        {{- end }}
        imagePullPolicy: {{ .Values.application.image.pullPolicy }}
        command:
          - /bin/sh
          - -c
          - |
            until (nc -vz $DB_HOST 5432);
            do
                echo "waiting for Postgresql"; sleep 1;
            done
            python3 manage.py migrate
            echo "DONE"
        resources:
          {{- toYaml .Values.application.migrate.resources | nindent 12 }}
{{- end }}
