apiVersion: v1
kind: Service
metadata:
  name: {{ include "sunflower.fullname" . }}-celery-worker
  labels:
    {{- include "sunflower.labels.celery" . | nindent 4 }}
spec:
  type: {{ .Values.celery.service.type }}
  ports:
    - port: {{ .Values.celery.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sunflower.selectorLabels.celery" . | nindent 4 }}
    celery: worker
