apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sunflower.fullname" . }}-application
  labels:
    {{- include "sunflower.labels.application" . | nindent 4 }}
data:
{{- range $conf_key,$conf_value := .Values.application.configs }}
  {{ $conf_key  }}: {{ $conf_value | quote }}
{{- end}}
  DB_HOST: {{ .Release.Name }}-postgresql
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sunflower.fullname" . }}-celery
  labels:
    {{- include "sunflower.labels.celery" . | nindent 4 }}
data:
{{- range $conf_key,$conf_value := .Values.celery.configs }}
  {{ $conf_key  }}: {{ $conf_value | quote }}
{{- end}}
  DB_HOST: {{ .Release.Name }}-postgresql
