apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sunflower.fullname" . }}
  labels:
    {{- include "sunflower.labels" . | nindent 4 }}
data:
{{- range $conf_key,$conf_value := .Values.configs }}
  {{ $conf_key  }}: {{ $conf_value | quote }}
{{- end}}
  DB_HOST: {{ .Release.Name }}-postgresql
