apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sunflower.fullname" . }}-application
  labels:
    {{- include "sunflower.labels.application" . | nindent 4 }}
data:

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sunflower.fullname" . }}-docs
  labels:
    {{- include "sunflower.labels.docs" . | nindent 4 }}
data:
