# Generated by Django 5.0.3 on 2024-03-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subjects", "0002_alter_subject_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="data",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Subject metadata"
            ),
        ),
    ]
