{{- if .Values.migrate.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-migrate-%s" (include "sunflower.fullname" .) (now | date "2006-01-02-15-04-05") | substr 0 60 }}
  labels:
    {{- include "sunflower.selectorLabels" . | nindent 4 }}
spec:
  backoffLimit: 15
  {{- if .Values.migrate.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ .Values.migrate.ttlSecondsAfterFinished }}
  {{- end }}
  template:
    metadata:
      name: {{ printf "%s-migrate-%s" (include "sunflower.fullname" .) (now | date "2006-01-02-15-04-05") }}
      {{- with .Values.podAnnotations }}
      annotations:
        random-annotation: {{ randAlphaNum 10 | lower }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sunflower.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sunflower.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}-migrate
        envFrom:
        - configMapRef:
            name: {{ include "sunflower.fullname" . }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        {{- if .Values.werf }}
        image: "{{ index .Values.werf "nameless_image"}}"
        {{- else }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: files
          mountPath: "/mnt/files"
          readOnly: true
        command:
          - /bin/sh
          - -c
          - |
            until (nc -vz $POSTGRES_SERVER 5432);
            do
                echo "waiting for Postgresql"; sleep 1;
            done
            echo "DONE"
        resources:
          {{- toYaml .Values.migrate.resources | nindent 12 }}
      volumes:
        - name: files
          secret:
            secretName: {{ include "sunflower.fullname" . }}-files
            optional: false

{{- end }}
