{{- if .Values.dockerconfigjson -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sunflower.fullname" . }}-registrysecret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{{ .Values.dockerconfigjson }}'
{{- end -}}
