{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sunflower.serviceAccountName" . }}
  labels:
    {{- include "sunflower.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.dockerconfigjson }}
imagePullSecrets:
  - name: {{ include "sunflower.fullname" . }}-registrysecret
{{- end }}
{{- end }}
