apiVersion: v2
name: sunflower
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.0.1"
dependencies:
  - name: postgresql
    version: 12.1.9
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 18.17.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
