envUrl: ".sbereducation.ru"
nodeSelector:
  node-role.kubernetes.io/dmz: ""
tolerations:
  - key: "node-role.kubernetes.io/dmz"
    operator: "Exists"
    effect: "NoSchedule"

application:
  configs:
    FORCE_SCRIPT_NAME: "/"

  ocsp:
    ingress:
      tlsSecretName: sbereducation.ru

  api:
    ingress:
      tlsSecretName: sbereducation.ru

  crl:
    ingress:
      tlsSecretName: sbereducation.ru
