{{- if .Values.werf -}}
{{- $fullName := include "sunflower.fullname" . -}}
{{- $svcPort := .Values.application.service.port -}}
{{- if and .Values.application.api.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.application.api.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.application.api.ingress.annotations "kubernetes.io/ingress.class" .Values.application.api.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-application-api
  labels:
    {{- include "sunflower.labels.application" . | nindent 4 }}
  {{- with .Values.application.api.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: nginx-external
  tls:
    - hosts:
        - "api{{ .Values.envUrl }}"
      secretName: {{ .Values.application.api.ingress.tlsSecretName }}
  rules:
    {{- range .Values.application.api.ingress.hosts }}
    - host: "api{{ $.Values.envUrl }}"
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-application
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}-application
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
  {{- end }}
