{{- if .Values.application.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sunflower.serviceAccountName.application" . }}
  labels:
    {{- include "sunflower.labels.application" . | nindent 4 }}
  {{- with .Values.application.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.application.dockerconfigjson }}
imagePullSecrets:
  - name: {{ include "sunflower.fullname" . }}-registrysecret
{{- end }}
{{- end }}
