apiVersion: v1
kind: Service
metadata:
  name: {{ include "sunflower.fullname" . }}-application
  labels:
    {{- include "sunflower.labels.application" . | nindent 4 }}
spec:
  type: {{ .Values.application.service.type }}
  ports:
    - port: {{ .Values.application.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sunflower.selectorLabels.application" . | nindent 4 }}
