# Generated by Django 4.2 on 2023-06-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("x509", "0002_certificate_revocation_reason_certificate_revoked_at_and_more")
    ]

    operations = [
        migrations.AddField(
            model_name="csr",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, unique=True, verbose_name="Slug"
            ),
        )
    ]
