# Generated by Django 4.2.3 on 2023-07-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("x509", "0003_csr_slug")]

    operations = [
        migrations.AlterModelOptions(
            name="certificate", options={"ordering": ["-created_at"]}
        ),
        migrations.AlterModelOptions(name="csr", options={"ordering": ["-created_at"]}),
        migrations.AlterModelOptions(name="key", options={"ordering": ["-created_at"]}),
        migrations.AddField(
            model_name="certificate",
            name="sn",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Serial number"
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="body",
            field=models.TextField(blank=True, verbose_name="Certificate"),
        ),
    ]
