# Generated by Django 4.2.6 on 2023-10-25 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("x509", "0006_certificate_fingerprint_certificate_key_hash_and_more")
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="key",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.RESTRICT, to="x509.key"
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="csr",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.RESTRICT, to="x509.csr"
            ),
        ),
        migrations.AlterField(
            model_name="key",
            name="private",
            field=models.TextField(blank=True, null=True, verbose_name="Private part"),
        ),
    ]
