# Generated by Django 4.2.6 on 2023-10-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("x509", "0007_certificate_key_alter_certificate_csr_and_more")]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="imported",
            field=models.BooleanField(default=False, verbose_name="Imported"),
        )
    ]
