# Generated by Django 4.2.7 on 2023-11-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("x509", "0008_certificate_imported"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="imported",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Imported"
            ),
        ),
    ]
