# Generated by Django 4.2.7 on 2023-11-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("x509", "0009_alter_certificate_imported"),
    ]

    operations = [
        migrations.AddField(
            model_name="csr",
            name="extended_key_usage",
            field=models.JSONField(
                blank=True, default={}, verbose_name="Extended Key Usage"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="csr",
            name="key_usage",
            field=models.JSONField(blank=True, default={}, verbose_name="Key Usage"),
            preserve_default=False,
        ),
    ]
