name: External Deployment
permissions: write-all
on:
  push:
    branches: [main]
jobs:

  converge:
    name: Converge
    runs-on: ubuntu-latest
    environment:
      name: external
      url: https://external.com
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Converge
        uses: werf/actions/converge@v1.2
        with:
          env: external
          kube-config-base64-data: ${{ secrets.KUBE_CONFIG_EXTERNAL_BASE64_DATA }}
        env:
          WERF_SECRET_KEY: ${{ secrets.WERF_SECRET_KEY }}
          WERF_SET_ENV_URL: "envUrl=${{ secrets.WERF_EXTERNAL_URL }}"
          WERF_NAMESPACE: "cis-sunflower-external"
          WERF_VALUES_1: ".helm/values_external.yaml"
          WERF_SECRET_VALUES_1: ".helm/values_external_secret.yaml"
