name: Production Deployment
permissions: write-all
on:
  push:
    branches: [main]
jobs:

  converge:
    name: Converge
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://stage.sunflower.ing
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Converge
        uses: werf/actions/converge@v1.2
        with:
          env: production
          kube-config-base64-data: ${{ secrets.KUBE_CONFIG_BASE64_DATA }}
        env:
          WERF_SECRET_KEY: ${{ secrets.WERF_SECRET_KEY }}
          WERF_SET_ENV_URL: "envUrl=.sunflower.ing"
