name: Staging Deployment
on:
  push:
    branches: [stage]
jobs:

  converge:
    name: Converge
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://stage.sunflower3455.com
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Converge
        uses: werf/actions/converge@v1.2
        with:
          env: staging
          kube-config-base64-data: ${{ secrets.KUBE_CONFIG_BASE64_DATA }}
        env:
          WERF_SECRET_KEY: ${{ secrets.WERF_SECRET_KEY }}
          WERF_SET_ENV_URL: "envUrl=stage.sunflower3455.com"
          WERF_LOG_DEBUG: "true"
